AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  MaxOptionalParameters: 6
  Max: 8

Metrics/AbcSize:
  CountRepeatedAttributes: false
